<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'ps1609');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'wYizBepxDzb4Zfry4uUvZPf08SyQuey3JBWROQ3bQnLDnj7bnzFy5fMQ');
define('_COOKIE_IV_', 'RKX4GREr');
define('_PS_CREATION_DATE_', '2014-09-03');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '5bHxfLqGMqgGL6yUvcgiMOmDy1EkoESo');
define('_RIJNDAEL_IV_', '1lcHFLXMZGZr/TsonTLzYQ==');
